name: review
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  smooth_star_rating_null_safety: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Jaapokki
      fonts:
        - asset: assets/fonts/jaapokkienchance-regular.ttf
